build:
	gcc mutex.c -o mutex -lpthread -Wall
	gcc barrier.c -o barrier -lpthread -Wall
	gcc multiply_seq.c -o multiply_seq -lpthread -Wall
	gcc multiply_i.c -o multiply_i -lpthread -Wall
	gcc multiply_j.c -o multiply_j -lpthread -Wall
	gcc multiply_k.c -o multiply_k -lpthread -Wall
	gcc strassen.c -o strassen -lpthread -Wall
	gcc strassen_par.c -o strassen_par -lpthread -Wall
clean:
	rm -rf mutex barrier multiply_seq multiply multiply_i multiply_j multiply_k strassen strassen_par
