build:
	gcc oets.c -o oets -lpthread -lm -Wall
	gcc shear.c -o shear -lpthread -lm -Wall
	gcc merge.c -o merge -lpthread -lm -Wall
	
shear_bad:
	gcc shear_bad.c -o shear_bad -lpthread -lm -Wall

clean:
	rm -rf oets shear merge shear_bad
